name: build_check

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - 'version/**'
  pull_request:
    branches:
      - main
      - 'version/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --no-restore
      working-directory: src
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src
